### Numpy (Numeric Python)

### Matematik bilimindeki işlemleri yapabilen aşırı hızlı bir kütüphane. (C ve Fortran dilinde yazılması)

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
## ndarray -> N Dimension

np_arr = np.array([1,2,3,4,5])
np_arr

array([1, 2, 3, 4, 5])

In [5]:
python_arr = [10,20,30,40,50]
python_arr

[10, 20, 30, 40, 50]

In [6]:
type(np_arr), type(python_arr)

(numpy.ndarray, list)

In [7]:
p_array2 = list(range(1_000_000))
n_array2 = np.array(p_array2)

In [8]:
%%timeit
[x+1 for x in p_array2] # p_array2deki her elemana bir ekle

46.2 ms ± 708 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%%timeit
n_array2 + 1 # n_array2'deki her elemana bir ekle

1.4 ms ± 26 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
n_array2.shape

(1000000,)

In [13]:
n_array2.ndim # n dimension

1

### Numpyda 10 adet özellik-fonksiyon araştırıp kullanım amaçlarıyla birlikte örneklendirdiğimiz bir ipynb dosyası hazırlayalım.

In [14]:
### Vectorler, Matrisler, Tensorler

In [5]:
import numpy as np
scalar_arr = np.array( 1 )
# ndim -> n dimension (Kaç boyutlu?)
# shape -> şekil?
scalar_arr.ndim, scalar_arr.shape

(0, ())

In [6]:
vector_arr = np.array( [10,20,30] )
vector_arr.ndim, vector_arr.shape # 1D, (3,)

(1, (3,))

In [7]:
matrix_arr = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)
matrix_arr.ndim, matrix_arr.shape

(2, (2, 3))

In [8]:
matrix_arr2 = np.array(
    [
        [70,80,90],
        [100,110,120]
    ]
)
matrix_arr2.ndim, matrix_arr.shape

(2, (2, 3))

In [11]:
# Şekiller uyuşuyor ise! 4 işlem yapılabilir.
result = matrix_arr + matrix_arr2
result

array([[ 80, 100, 120],
       [140, 160, 180]])

In [10]:
result2 = matrix_arr * matrix_arr2
result2

array([[ 700, 1600, 2700],
       [4000, 5500, 7200]])

In [12]:
matrix_arr3 = np.array(
    [
        [100,120],
        [140, 160],
        [180, 200]
    ]
)
matrix_arr3.shape

(3, 2)

In [19]:
#result3 = matrix_arr2 + matrix_arr3

In [18]:
# Reshape işlemi
result3 = matrix_arr2 + matrix_arr3.reshape(2,3)
result3

array([[170, 200, 230],
       [260, 290, 320]])

In [20]:
# 3D+ arrayler -> Tensör
tensor_arr = np.array(
    [
        [ [1,2,3,4], [5,6,7,8]  ],
        [ [9,10,11,12], [13,14,15,16]  ],
        [ [17,18,19,20], [21,22,23,24]  ]
    ]
)
tensor_arr.ndim, tensor_arr.shape
# satır,sütun, sütundaki eleman sayısı

(3, (3, 2, 4))

In [21]:
!pip install Pillow

In [22]:
from PIL import Image

cat_img = Image.open("kedi.jpg")

In [25]:
cat_img_arr = np.array(cat_img)
cat_img_arr.ndim, cat_img_arr.shape

(3, (1500, 1000, 3))

In [28]:
cat_img_arr[1250]

array([[13,  7,  9],
       [13,  7,  9],
       [13,  7,  9],
       ...,
       [76, 56, 47],
       [72, 52, 43],
       [71, 51, 42]], shape=(1000, 3), dtype=uint8)

In [29]:
image = np.random.randint(0,256, (100, 100, 3))
image

array([[[ 45, 199,  85],
        [  5, 238, 108],
        [122,  83, 106],
        ...,
        [ 47,  17,  11],
        [156, 147, 148],
        [151,  98,  98]],

       [[115,  52, 121],
        [209, 137, 159],
        [ 23, 235,   5],
        ...,
        [130, 169, 216],
        [ 23,  95, 160],
        [ 52,  60, 253]],

       [[ 90, 146,  91],
        [ 26,  78, 212],
        [132, 154, 188],
        ...,
        [133,  25,  26],
        [ 22,   1, 203],
        [ 60,  61, 119]],

       ...,

       [[161, 202, 121],
        [ 88, 250, 227],
        [136, 248, 176],
        ...,
        [163, 211,  18],
        [ 69, 221,  73],
        [ 78,  10,  65]],

       [[ 94, 239, 236],
        [253, 179,  83],
        [ 61, 127, 151],
        ...,
        [158, 140, 108],
        [ 61, 209,  44],
        [ 57,  94,  47]],

       [[116,  84,  75],
        [104,  71, 238],
        [ 35,  70,  66],
        ...,
        [174,  54,  77],
        [240,  89, 242],
        [231, 240,  45]]